### ISSUE TITLE
Getting ready for first samples

### ISSUE THREAD

**Issue by remyblok** [pnp/powerautomate-samples#1]
Hi @hugoabernier,

Last week I heard in the Power Apps Community Call about the PnP site for Power Platform Samples. I think it is really interesting! I see that there are no samples for Power Automate yet and the repo is not yet set up. I have 2 or 3 patterns (to start with) that I think are useful to share here. They are mainly around error handing. I see that thing go wrong there other for people new to Power Automate.

Is there any way I can help do the initial setup of this repo? I can just take a good look at how things are setup in the PowerFX samples repo and bend that to Power Automate if you want.

Let me know,

Regards, Remy

**Comment by hugoabernier** [comment]
@remyblok thanks for reaching out!

You can definitely help set up the repo. 

I will set up the folder structure, templates, etc., but you can definitely make a pull request with individual samples in a separate sub folder under the `samples` folder. 

I'll copy the `Readme-template.md' from the `powerapp-samples`, but feel free to use it as a basis for the `Readme.md` for your samples.

For screenshots,  maybe we can use a screen shot of the flow,  or maybe zoom in on an area of interest?

Thanks for offering to help. I look forward to seeing the samples!
