### ISSUE TITLE
Link to the Sample is wrong. 

### ISSUE THREAD

**Issue by alisalih1** [pnp/powerautomate-samples#40]
### Sample

https://github.com/pnp/powerautomate-samples/tree/main/samples/azure-http-key-vault

### Author(s)

Divya Akula

### What happened?

While I understand that this is not a Bug directly related to the code provided, I've not found a way to raise awareness to this issue elsewhere.  

The GitHub link provided on [this page](https://adoption.microsoft.com/en-us/sample-solution-gallery/sample/pnp-powerautomate-samples-azure-http-key-vault/) is pointing to the wrong Sample in the PnP repository. 

The GitHub link is pointing to "Always respond to a request" sample, rather the "azure-http-key-vault" sample. In addition, the azure-http-key-vault sample's READ ME has a wrong title with "Pattern: Always respond to a request". It seems like a copy-paste gone wrong.

### Steps to reproduce

1. Visit https://adoption.microsoft.com/en-us/sample-solution-gallery/?product=Power+Automate&sortby=creationDateTime-true&page=1
2. Click on the View on GitHub
3. Observe that it is pulling up the wrong folder. 

### Expected behavior

It should pull up the correct code.

**Comment by ValerasNarbutas** [comment]
Hi @aprildunnam, 
i know you are very very busy, but maybe you could commit this?
Were is an incorrect link still on every community page we have for samples.

I can help with maintaining of this repo if needed.

Thanks, Valeras
