### ISSUE TITLE
Missing sample

### ISSUE THREAD

**Issue by MSUMOLL** [pnp/powerautomate-samples#44]
### Sample

https://github.com/pnp/powerautomate-samples/tree/main/samples/send-name-pronunciation-recording-to-library

### Author(s)

@IsheltonSTO

### What happened?

When clicking the [download link in the "minimal path to awesome" section](https://github.com/pnp/powerautomate-samples/tree/main/samples/send-name-pronunciation-recording-to-library#minimal-path-to-awesome) i get a 404 error. 

The sample .zip file does not seem to exist anywhere in the sample files. In fact, there is no solution folder. 

This flow is a [prerequisite for using the Name Pronunciation Recorder power app sample](https://github.com/pnp/powerapps-samples/tree/main/samples/name-pronunciation-recorder#prerequisites).

Thanks!

### Steps to reproduce

1. go to https://github.com/pnp/powerautomate-samples/tree/main/samples/send-name-pronunciation-recording-to-library#minimal-path-to-awesome
2. Click Download
3. Get 404

### Expected behavior

I expect to be able to download the file, but the file does not seem to exist in the repo.

**Comment by ValerasNarbutas** [comment]
thanks, @MSUMOLL , 
i have checked this solution commit, looks like zip was never added. I might create it and update it. meanwhile, you could use source folder and create zip from it. Should work also.

**Comment by MSUMOLL** [comment]
Thanks for the workaround. I didn't realize the source could be zipped and imported in that way.

**Comment by MSUMOLL** [comment]
> thanks, @MSUMOLL , i have checked this solution commit, looks like zip was never added. I might create it and update it. meanwhile, you could use source folder and create zip from it. Should work also.

I copied source folder and created zip. Got an error when importing. Any pointers?

**Comment by Laskewitz** [comment]
> > thanks, @MSUMOLL , i have checked this solution commit, looks like zip was never added. I might create it and update it. meanwhile, you could use source folder and create zip from it. Should work also.
> 
> 
> 
> I copied source folder and created zip. Got an error when importing. Any pointers?

Sorry for the late reply. This sample has been combined with the Power Apps sample with the same name. You can use the sample here: https://github.com/pnp/powerapps-samples/tree/main/samples/name-pronunciation-recorder

**Comment by MSUMOLL** [comment]
Thanks!. The instructions on that project still indicate that this needs to be downloaded and installed first. 

https://github.com/pnp/powerapps-samples/tree/main/samples/name-pronunciation-recorder#prerequisites.

**Comment by Laskewitz** [comment]
> Thanks!. The instructions on that project still indicate that this needs to be downloaded and installed first. 
> 
> 
> 
> https://github.com/pnp/powerapps-samples/tree/main/samples/name-pronunciation-recorder#prerequisites. 

You don't need to. I'll fix the readme soon.

**Comment by MSUMOLL** [comment]
Thanks!
