### ISSUE TITLE
Error when Importing

### ISSUE THREAD

**Issue by Beroshge** [pnp/powerautomate-samples#49]
### Sample

https://github.com/pnp/powerautomate-samples/tree/main/samples/convert-sharepoint-library-doc-file-to-pdf

### Author(s)

@RapidCircle

### What happened?

The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

### Steps to reproduce

Open Power Platform
2. Solutions 
3. Import
4.Point to file click open

### Expected behavior

I expect the solution to import.

**Comment by Beroshge** [comment]
My mistake

**Comment by NL12143** [comment]
Yes anoying for us but imagine a normal user to give PnP samples a try ... adoption down the drain. 
Refer my idea to use proper naming conventions.
