### ISSUE TITLE
wrong author

### ISSUE THREAD

**Issue by LuiseFreese** [pnp/powerautomate-samples#9]
### Sample

https://github.com/pnp/powerautomate-samples/tree/main/samples/Try-Catch-Finally

### Author(s)

@CarlCooksen

### What happened?

In the sample browser it appears as if Carl Cooksen was the author for this sample, but actually it was Pieter Veenstra, which can be found in the README.md about this sample as well. 

Carl informed me about this issue :-) Can you please have a look so that the actual authors get credit? 

![image](https://user-images.githubusercontent.com/49960482/117284937-af3ff180-ae67-11eb-805d-ae77dd70a503.png)

### Steps to reproduce

1. open the sample browser at https://pnp.github.io/powerplatform-samples/
2. find the Power Automate samples from Carl Cooksen (**Try-Catch-Finally** and **exception-handing-in-do-until-loop**
3. check README.md files for author names

### Expected behavior

I expected the correct author to appear in the sample browser

**Comment by hugoabernier** [comment]
Thank you @LuiseFreese. The README template indicates the following:

> One author per line, please DELETE THIS PARAGRAPH BEFORE SUBMITTING

I assume from the README comments that the author was Carl, with credit to the blog author.

We welcome pull requests if you wish to make the changes :-)

**Comment by hugoabernier** [comment]
Fixed the `sample.json` to point to the right author.
